plugins {
    id 'com.android.application'
}

android {
    namespace 'app.streamy2.admin'
    compileSdk 36

    defaultConfig {
        applicationId "app.streamy2.admin"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
